Repository dgw/sopel-waifu, pull requests merged in 2024-02, with the labels that each got.

#29 Remove `fgowaifu` and add `fmk` commands
  sopel_waifu/__init__.py
Labels: enhancement

#31 Correctly generate three choices for `fmk` command
  sopel_waifu/__init__.py
Labels: bugfix

#30 Refactor hard-coded memory keys to module-level constants
  sopel_waifu/__init__.py
Labels: enhancement

#33 Use `random.sample()` for `fmk` selection
  sopel_waifu/__init__.py
Labels: enhancement

#35 Write waifu suggestions directly to a file
  sopel_waifu/__init__.py
Labels: enhancement

#37 Handle formatting escape sequences (`$c` only for now) at setup time
  sopel_waifu/__init__.py
Labels: enhancement

#36 Add output prefix to all commands
  sopel_waifu/__init__.py
Labels: enhancement

#38 Remove `(F/GO)` suffix from the list and from loading handler
  sopel_waifu/__init__.py
  sopel_waifu/waifu.json
Labels: enhancement, data
